export const categories = [
    { name: "Design companies", color: "#00ff6a" },
    { name: "Retail", color: "#00ff6a" },
    { name: "Food and Beverages", color: "#00ff6a" },
    { name: "Medical + Cosmetics", color: "#00ff6a" },
    { name: "Media + Culture", color: "#00ff6a" },
    { name: "Conference + Hotel + Real Estate", color: "#00ff6a" },
    { name: "Placebranding + Travel", color: "#00ff6a" },
    { name: "Unions", color: "#00ff6a" },
    { name: "Education", color: "#00ff6a" },
    { name: "Finance", color: "#00ff6a" },
    { name: "Tele", color: "#00ff6a" },
    { name: "Officials", color: "#00ff6a" },
    { name: "Funds", color: "#00ff6a" },
    { name: "NGOs", color: "#00ff6a" },
    { name: "Transport", color: "#00ff6a" }
]

export const cases = [
    { name: "Royal Copenhagen", category: "Design companies" },
    { name: "Montana", category: "Design companies" },
    { name: "Fritz Hansen", category: "Design companies" },
    { name: "Dinesen", category: "Design companies" },
    { name: "Bang & Olufsen", category: "Design companies" },
    { name: " Bodum", category: "Design companies" },
    { name: "Eva Solo", category: "Design companies" },
    { name: "iittala", category: "Design companies" },
    { name: "Faber", category: "Design companies" },
    { name: "IKEA", category: "Design companies" },
    { name: "Inspiration", category: "Retail" },
    { name: "BOOZT", category: "Retail" },
    { name: "Ilum", category: "Retail" },
    { name: "Magasin", category: "Retail" },
    { name: "CPH Airport", category: "Retail" },
    { name: "Ro's Torv", category: "Retail" },
    { name: "Bahne", category: "Retail" },
    { name: "B.R. Legetøj", category: "Retail" },
    { name: "Irma", category: "Retail" },
    { name: "tff", category: "Retail" },
    { name: "Lilly", category: "Food and Beverages" },
    { name: "Nescafé", category: "Food and Beverages" },
    { name: "Bornholms Mosteri", category: "Food and Beverages" },
    { name: "Arla", category: "Food and Beverages" },
    { name: "Ramlösa", category: "Food and Beverages" },
    { name: "Egekilde", category: "Food and Beverages" },
    { name: "Sven Michelsen", category: "Food and Beverages" },
    { name: "Nicoline Sodavand", category: "Food and Beverages" },
    { name: "Malthesers", category: "Food and Beverages" },
    { name: "Cheasy", category: "Food and Beverages" },
    { name: "De Danske Spritfabrikker", category: "Food and Beverages" },
    { name: "Vapiano", category: "Food and Beverages" },
    { name: "House of Prince", category: "Food and Beverages" },
    { name: "P & G", category: "Medical + Cosmetics" },
    { name: "AKA", category: "Medical + Cosmetics" },
    { name: "Decubal", category: "Medical + Cosmetics" },
    { name: "Astalou", category: "Medical + Cosmetics" },
    { name: "Rudolph Care", category: "Medical + Cosmetics" },
    { name: "LEO Pharma", category: "Medical + Cosmetics" },
    { name: "Genmab", category: "Medical + Cosmetics" },
    { name: "Multi Tabs", category: "Medical + Cosmetics" },
    { name: "Tv2", category: "Media + Culture" },
    { name: "Information", category: "Media + Culture" },
    { name: "CNN", category: "Media + Culture" },
    { name: "BØRSEN", category: "Media + Culture" },
    { name: "Berlingske Tidende", category: "Media + Culture" },
    { name: "Gyldendal", category: "Media + Culture" },
    { name: "Benjamin Media", category: "Media + Culture" },
    { name: "Nørrebro Teater", category: "Media + Culture" },
    { name: "Øster Gasværk Teater", category: "Media + Culture" },
    { name: "Det Kongelige Teater", category: "Media + Culture" },
    { name: "Søhuset Konferencecenter", category: "Conference + Hotel + Real Estate" },
    { name: "Kongebrogaarden", category: "Conference + Hotel + Real Estate" },
    { name: "Great Northern", category: "Conference + Hotel + Real Estate" },
    { name: "Square Meter", category: "Conference + Hotel + Real Estate" },
    { name: "The Archive House", category: "Conference + Hotel + Real Estate" },
    { name: "The Mark", category: "Conference + Hotel + Real Estate" },
    { name: "Odense", category: "Placebranding + Travel" },
    { name: "Tønder Marsken", category: "Placebranding + Travel" },
    { name: "Topas Rejser", category: "Placebranding + Travel" },
    { name: "BUPL", category: "Unions" },
    { name: "Djøf", category: "Unions" },
    { name: "Dansk Industri", category: "Unions" },
    { name: "DTU", category: "Education" },
    { name: "KEA", category: "Education" },
    { name: "MSD", category: "Education" },
    { name: "Deloitte", category: "Finance" },
    { name: "Skandia Pension", category: "Finance" },
    { name: "Carnegie", category: "Finance" },
    { name: "TDC", category: "Tele" },
    { name: "Telia", category: "Tele" },
    { name: "Justitsministeriet", category: "Officials" },
    { name: "Det Kriminalpræventive Råd", category: "Officials" },
    { name: "Ministeriet for Børn, Undervisning og Ligestilling", category: "Officials" },
    { name: "Sundhedsstyrelsen", category: "Officials" },
    { name: "TrygFonden", category: "Funds" },
    { name: "A.P. Møllerfonden", category: "Funds" },
    { name: "Friluftsrådet", category: "NGOs" },
    { name: "Gigtforeningen", category: "NGOs" },
    { name: "Diabetesforeningen", category: "NGOs" },
    { name: "Kræftens Bekæmpelse", category: "NGOs" },
    { name: "Aids Fondet", category: "NGOs" },
    { name: "Red Barnet", category: "NGOs" },
    { name: "Kirkens Korshær", category: "NGOs" },
    { name: "SOS Børnebyerne", category: "NGOs" },
    { name: "Amnesty International", category: "NGOs" },
    { name: "Mellemfolkeligt Samvirke", category: "NGOs" },
    { name: "Danmarks Indsamling", category: "NGOs" },
    { name: "DSB", category: "Transport" },
    { name: "Københavns Metro", category: "Transport" },

]
